const ContactActionTypes = {
  FETCH_CONTACT_DETAILS_START: 'FETCH_CONTACT_DETAILS_START',
  FETCH_CONTACT_DETAILS_SUCCESS: 'FETCH_CONTACT_DETAILS_SUCCESS',
  FETCH_CONTACT_DETAILS_FAILURE: 'FETCH_CONTACT_DETAILS_FAILURE'
}

export default ContactActionTypes;
