const ShopActionTypes = {
  FETCH_SECTIONS_START: 'FETCH_SECTIONS_START',
  FETCH_SECTIONS_SUCCESS: 'FETCH_SECTIONS_SUCCESS',
  FETCH_SECTIONS_FAILURE: 'FETCH_SECTIONS_FAILURE'
}

export default ShopActionTypes;
